
package com.currency.convertor.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.mule.api.MuleEventContext;
import org.mule.api.lifecycle.Callable;
import org.mule.api.MuleMessage;
import org.mule.module.http.internal.ParameterMap;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-09-03T18:12:20.802-03:00
 * Generated source version: 2.5.1
 * 
 */
public final class WSConsumerCurrencyConvertor implements Callable{

    private static final QName SERVICE_NAME = new QName("http://www.webserviceX.NET/", "CurrencyConvertor");

    public WSConsumerCurrencyConvertor() {
    	
    }
    
    @Override
	public Object onCall(MuleEventContext eventContext) throws Exception {
        
    	MuleMessage message = eventContext.getMessage();
    	ParameterMap httpQueryParams = message.getInboundProperty("http.query.params");
    	
    	URL wsdlURL = CurrencyConvertor.WSDL_LOCATION;
         
        File wsdlFile = new File("http://www.webservicex.net/CurrencyConvertor.asmx?WSDL");
        try {
            if (wsdlFile.exists()) {
                wsdlURL = wsdlFile.toURI().toURL();
            } else {
                wsdlURL = new URL("http://www.webservicex.net/CurrencyConvertor.asmx?WSDL");
            }
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        
      
        CurrencyConvertor ss = new CurrencyConvertor(wsdlURL, SERVICE_NAME);
        CurrencyConvertorSoap port = ss.getCurrencyConvertorSoap();  

        System.out.println("Invoking conversionRate...");
        java.lang.String _conversionRate_fromCurrency = httpQueryParams.get("from");
        java.lang.String _conversionRate_toCurrency = httpQueryParams.get("to");
        double _conversionRate__return = port.conversionRate(_conversionRate_fromCurrency, _conversionRate_toCurrency);
        System.out.println("conversionRate.result=" + _conversionRate__return);
        message.setPayload(_conversionRate__return);
        
        return message.getPayload();
    	
    }
    

}
