
package com.banks.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;
import javax.xml.namespace.QName;
import org.mule.api.MuleEventContext;
import org.mule.api.MuleMessage;
import org.mule.api.lifecycle.Callable;
import org.mule.module.http.internal.ParameterMap;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-09-16T17:37:24.793-03:00
 * Generated source version: 2.5.1
 * 
 */
public class WSConsumerBankFinder implements Callable{

    private static final QName SERVICE_NAME = new QName("http://thomas-bayer.com/blz/", "BLZService");

    public WSConsumerBankFinder() {
    }
    
    @Override
    public Object onCall(MuleEventContext eventContext) throws Exception {
    	
    	MuleMessage message = eventContext.getMessage();
    	ParameterMap httpQueryParams = message.getInboundProperty("http.query.params");
    	
        URL wsdlURL = BLZService.WSDL_LOCATION;
      
        BLZService ss = new BLZService(wsdlURL, SERVICE_NAME);
        BLZServicePortType port = ss.getBLZServiceSOAP11PortHttp();  
        
        System.out.println("Invoking getBank...");
        java.lang.String _getBank_blz = httpQueryParams.get("blz");
        com.banks.client.DetailsType _getBank__return = port.getBank(_getBank_blz);
        System.out.println("getBank.result=" + _getBank__return);

        return _getBank__return;
    }

}
