package com.hello.name.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-09-11T15:50:52.293-03:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://nks34.t320", name = "HelloServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloServicePortType {

    @WebMethod(action = "urn:helloName")
    @Action(input = "urn:helloName", output = "urn:helloNameResponse")
    @RequestWrapper(localName = "helloName", targetNamespace = "http://nks34.t320", className = "uk.hello.name.client.HelloName")
    @ResponseWrapper(localName = "helloNameResponse", targetNamespace = "http://nks34.t320", className = "uk.hello.name.client.HelloNameResponse")
    @WebResult(name = "return", targetNamespace = "http://nks34.t320")
    public java.lang.String helloName(
        @WebParam(name = "name", targetNamespace = "http://nks34.t320")
        java.lang.String name
    );
}
