
package com.hello.name.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.mule.api.MuleEventContext;
import org.mule.api.MuleMessage;
import org.mule.api.lifecycle.Callable;
import org.mule.module.http.internal.ParameterMap;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-09-11T15:50:52.267-03:00
 * Generated source version: 2.5.1
 * 
 */
public final class WSConsumerHelloName implements Callable{

    private static final QName SERVICE_NAME = new QName("http://nks34.t320", "HelloService");

    public WSConsumerHelloName() {
    	
    }
    
    @Override
    public Object onCall(MuleEventContext eventContext) throws Exception {
    	
    	MuleMessage message = eventContext.getMessage();
    	ParameterMap httpQueryParams = message.getInboundProperty("http.query.params");
        
    	URL wsdlURL = HelloService.WSDL_LOCATION;
        
        File wsdlFile = new File("http://t320webservices.open.ac.uk/t320/services/HelloService?wsdl");
        try {
            if (wsdlFile.exists()) {
                wsdlURL = wsdlFile.toURI().toURL();
            } else {
                wsdlURL = new URL("http://t320webservices.open.ac.uk/t320/services/HelloService?wsdl");
            }
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        
      
        HelloService ss = new HelloService(wsdlURL, SERVICE_NAME);
        HelloServicePortType port = ss.getHelloServiceSOAP11PortHttp1();  
        
        System.out.println("Invoking helloName...");
        java.lang.String _helloName_name = httpQueryParams.get("name");
        java.lang.String _helloName__return = port.helloName(_helloName_name);
        System.out.println("helloName.result=" + _helloName__return);
        

        return _helloName__return;
    }

}
