package com.temp.convertor.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-09-08T18:16:17.602-03:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://www.w3schools.com/webservices/", name = "TempConvertSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TempConvertSoap {

    @WebMethod(operationName = "CelsiusToFahrenheit", action = "http://www.w3schools.com/webservices/CelsiusToFahrenheit")
    @RequestWrapper(localName = "CelsiusToFahrenheit", targetNamespace = "http://www.w3schools.com/webservices/", className = "com.w3.temp.client.CelsiusToFahrenheit")
    @ResponseWrapper(localName = "CelsiusToFahrenheitResponse", targetNamespace = "http://www.w3schools.com/webservices/", className = "com.w3.temp.client.CelsiusToFahrenheitResponse")
    @WebResult(name = "CelsiusToFahrenheitResult", targetNamespace = "http://www.w3schools.com/webservices/")
    public java.lang.String celsiusToFahrenheit(
        @WebParam(name = "Celsius", targetNamespace = "http://www.w3schools.com/webservices/")
        java.lang.String celsius
    );

    @WebMethod(operationName = "FahrenheitToCelsius", action = "http://www.w3schools.com/webservices/FahrenheitToCelsius")
    @RequestWrapper(localName = "FahrenheitToCelsius", targetNamespace = "http://www.w3schools.com/webservices/", className = "com.w3.temp.client.FahrenheitToCelsius")
    @ResponseWrapper(localName = "FahrenheitToCelsiusResponse", targetNamespace = "http://www.w3schools.com/webservices/", className = "com.w3.temp.client.FahrenheitToCelsiusResponse")
    @WebResult(name = "FahrenheitToCelsiusResult", targetNamespace = "http://www.w3schools.com/webservices/")
    public java.lang.String fahrenheitToCelsius(
        @WebParam(name = "Fahrenheit", targetNamespace = "http://www.w3schools.com/webservices/")
        java.lang.String fahrenheit
    );
}
